spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/dubbo?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 1234

server:
  port: 8083


security:
  jwt:
    secret: k09BQnaF
    expiration: 604800 #7Days

logging:
  path: /var/log
  file: ycs-api.log
  level: debug

mybatis:
  config-location: classpath:mybatis-com.quchwe.common.config.xml
  mapper-locations: classpath:mybatis/*.xml

